---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Nectar App"
host: "localhost:10010"
basePath: "/"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /stockist:
    get:
      description: "Returns a stockist"
      operationId: "get_stockist"
      parameters:
      - name: "name"
        in: "query"
        description: "Returns a stockist"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/stockist"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
    post:
      description: "Add a Stockist to the Stockist Lists"
      operationId: "add_stockists"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/stockist"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/stockist"
        405:
          description: "Invalid input"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
    delete:
      description: "Deletes a stockist"
      operationId: "delete_stockist"
      parameters:
      - name: "name"
        in: "query"
        description: "Deletes a stockist"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/stockist"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
  /stockist/{name}:
    get:
      description: "Returns the stockist with supplied name"
      operationId: "get_stockist_by_name"
      parameters:
      - name: "name"
        in: "path"
        description: "Returns the stockist"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/stockist"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
  /allStockists:
    get:
      description: "Returns all stockists"
      operationId: "get_all_stockists"
      parameters: []
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/stockist"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
  /contacts:
    get:
      description: "Returns a contact"
      operationId: "get_contact"
      parameters:
      - name: "name"
        in: "query"
        description: "Returns a contact"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/contact"
        401:
          description: "No contacts matching that name"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
    post:
      description: "Add a contact to the Stockist Lists"
      operationId: "add_contact"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/contact"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/contact"
        405:
          description: "Invalid input"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
    delete:
      description: "Deletes a contact"
      operationId: "delete_contact"
      parameters:
      - name: "name"
        in: "query"
        description: "Deletes a contact"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/contact"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
  /socialMedia:
    get:
      description: "Returns a social_media item"
      operationId: "get_social_media"
      parameters:
      - name: "name"
        in: "query"
        description: "Returns a social_media item"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/social_media"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
    post:
      description: "Add an social_media to the Stockist Lists"
      operationId: "add_social_media"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/social_media"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/social_media"
        405:
          description: "Invalid input"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
    delete:
      description: "Deletes a social_media item"
      operationId: "delete_social_media"
      parameters:
      - name: "name"
        in: "query"
        description: "Deletes a social_media item"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/social_media"
        default:
          description: "Error"
          schema:
            $ref: "#/definitions/error_response"
      x-swagger-router-controller: "Default"
  /swagger:
    x-swagger-pipe: "swagger_raw"
definitions:
  stockist:
    type: "object"
    properties:
      address:
        type: "string"
        example: "123 Test View Road, Auckland"
        minLength: 2
        maxLength: 100
      name:
        type: "string"
        example: "Test View SuperMarket"
        minLength: 2
        maxLength: 50
      location:
        $ref: "#/definitions/stockist_location"
    example:
      address: "123 Test View Road, Auckland"
      name: "Test View SuperMarket"
      location:
        lat: 0.80082819046101150206595775671303272247314453125
        long: 6.02745618307040320615897144307382404804229736328125
  contact:
    type: "object"
    properties:
      phone:
        type: "number"
        example: 92925555
      mobile:
        type: "number"
        example: 212925555
      email:
        type: "string"
        example: "test@email.com"
      address:
        type: "string"
        example: "123 Test View Road, Auckland"
    example:
      address: "123 Test View Road, Auckland"
      phone: 92925555
      mobile: 212925555
      email: "test@email.com"
  social_media:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Facebook"
      link:
        type: "string"
        example: "https://www.facebook.com/TestTag-729569190470643/?ref=br_rs"
    example:
      name: "Facebook"
      link: "https://www.facebook.com/TestTag-729569190470643/?ref=br_rs"
  error_response:
    required:
    - "message"
    properties:
      message:
        type: "string"
  stockist_location:
    properties:
      lat:
        type: "number"
      long:
        type: "number"
    example:
      lat: 0.80082819046101150206595775671303272247314453125
      long: 6.02745618307040320615897144307382404804229736328125
